### ISSUE TITLE
Build `bldr` binary for OS X/Linux/Windows (?)

### ISSUE THREAD

**Issue by smira** [siderolabs/bldr#27]
Might be useful for `graph`

**Comment by ammmze** [comment]
This would also be useful now with the Talos system extensions in its current form. I'm working on an extension and it appears when doing the `make`, it is trying to invoke `bldr`, but the `bldr` it downloaded on macOS is just a text file that says "Not Found" because there is no build for macOS.

**Comment by frezbo** [comment]
https://github.com/siderolabs/bldr/releases/tag/v0.2.0-alpha.10 should have a mac binary
